import type {
  User, Product, SwapRequest, Message, Rating,
  Report, Dispute, Transaction, Category, CoinPackage,
  AIRecommendation, SuspiciousActivity, SwapTimelineEvent,
} from '@/types'
import { PRODUCT_CATEGORIES } from '@/lib/product-categories'

const MOCK_SERVICE_FEE_EGP = Number(process.env.NEXT_PUBLIC_MOCK_SERVICE_FEE_EGP || 0)

// ── Users ─────────────────────────────────────────────────────

export const MOCK_USERS: User[] = [
  {
    id: 'user-1',
    firstName: 'Alex',
    lastName: 'Morgan',
    email: 'alex.morgan@email.com',
    phone: '+20 100 123 4567',
    avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=alex',
    country: 'Egypt',
    city: 'Cairo',
    streetAddress: '15 Tahrir Square, Downtown',
    bio: 'Tech enthusiast and book lover. I have lots of gadgets to trade!',
    joinedAt: '2023-08-15T10:00:00Z',
    isEmailVerified: true,
    isPhoneVerified: true,
    isAdmin: false,
    trustLevel: 'trusted',
    trustScore: 87,
    completedSwaps: 14,
    totalSwaps: 17,
    rating: 4.7,
    ratingCount: 12,
    coinBalance: 340,
    featuredSlotsUsed: 1,
    profileCompleteness: 95,
    isSuspended: false,
    lastActiveAt: '2024-03-20T14:30:00Z',
  },
  {
    id: 'user-2',
    firstName: 'Sara',
    lastName: 'Hassan',
    email: 'sara.hassan@email.com',
    phone: '+20 112 987 6543',
    avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=sara',
    country: 'Egypt',
    city: 'Alexandria',
    streetAddress: '42 Corniche Road, Sidi Gaber',
    bio: 'Fashion lover, always looking to refresh my wardrobe through swaps.',
    joinedAt: '2023-10-02T09:00:00Z',
    isEmailVerified: true,
    isPhoneVerified: false,
    isAdmin: false,
    trustLevel: 'trusted',
    trustScore: 76,
    completedSwaps: 8,
    totalSwaps: 10,
    rating: 4.4,
    ratingCount: 7,
    coinBalance: 180,
    featuredSlotsUsed: 0,
    profileCompleteness: 80,
    isSuspended: false,
    lastActiveAt: '2024-03-18T11:00:00Z',
  },
  {
    id: 'user-3',
    firstName: 'Omar',
    lastName: 'Khalil',
    email: 'omar.khalil@email.com',
    phone: '+20 101 555 7890',
    avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=omar',
    country: 'Egypt',
    city: 'Giza',
    bio: 'Sports gear and outdoor equipment trader.',
    joinedAt: '2024-01-10T08:00:00Z',
    isEmailVerified: true,
    isPhoneVerified: true,
    isAdmin: false,
    trustLevel: 'new',
    trustScore: 42,
    completedSwaps: 2,
    totalSwaps: 3,
    rating: 4.0,
    ratingCount: 2,
    coinBalance: 60,
    featuredSlotsUsed: 0,
    profileCompleteness: 65,
    isSuspended: false,
    lastActiveAt: '2024-03-19T16:00:00Z',
  },
  {
    id: 'user-4',
    firstName: 'Nour',
    lastName: 'Abdel Aziz',
    email: 'nour.aa@email.com',
    phone: '+20 100 222 3344',
    avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=nour',
    country: 'Egypt',
    city: 'Cairo',
    streetAddress: '7 Nasr City, Block 12',
    bio: 'Interior design enthusiast. Trading furniture, art, and home decor.',
    joinedAt: '2023-06-01T07:00:00Z',
    isEmailVerified: true,
    isPhoneVerified: true,
    isAdmin: false,
    trustLevel: 'trusted',
    trustScore: 94,
    completedSwaps: 22,
    totalSwaps: 24,
    rating: 4.9,
    ratingCount: 20,
    coinBalance: 720,
    featuredSlotsUsed: 2,
    profileCompleteness: 100,
    isSuspended: false,
    lastActiveAt: '2024-03-20T18:00:00Z',
  },
  {
    id: 'user-5',
    firstName: 'Karim',
    lastName: 'Farid',
    email: 'karim.farid@email.com',
    avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=karim',
    country: 'Egypt',
    city: 'Mansoura',
    joinedAt: '2024-02-20T12:00:00Z',
    isEmailVerified: false,
    isPhoneVerified: false,
    isAdmin: false,
    trustLevel: 'risky',
    trustScore: 18,
    completedSwaps: 0,
    totalSwaps: 2,
    rating: 0,
    ratingCount: 0,
    coinBalance: 20,
    featuredSlotsUsed: 0,
    profileCompleteness: 30,
    isSuspended: true,
    suspendedReason: 'Attempted external contact bypassing platform',
    lastActiveAt: '2024-02-28T09:00:00Z',
  },
  {
    id: 'admin-1',
    firstName: 'Admin',
    lastName: 'Team',
    email: 'admin@swapandsave.com',
    avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=admin',
    country: 'Egypt',
    city: 'Cairo',
    joinedAt: '2023-01-01T00:00:00Z',
    isEmailVerified: true,
    isPhoneVerified: true,
    isAdmin: true,
    trustLevel: 'trusted',
    trustScore: 100,
    completedSwaps: 0,
    totalSwaps: 0,
    rating: 0,
    ratingCount: 0,
    coinBalance: 0,
    featuredSlotsUsed: 0,
    profileCompleteness: 100,
    isSuspended: false,
    lastActiveAt: '2024-03-20T20:00:00Z',
  },
]

// The "current logged-in user" for mock purposes
export const CURRENT_USER_ID = 'user-1'
export const getCurrentUser = () => MOCK_USERS.find(u => u.id === CURRENT_USER_ID)!

// ── Products ──────────────────────────────────────────────────

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    ownerId: 'user-1',
    title: 'Sony WH-1000XM5 Wireless Headphones',
    description: 'Barely used noise-cancelling headphones. Amazing sound quality. Box included with all accessories. Used for only 2 months.',
    category: 'Electronics',
    subcategory: 'Audio',
    condition: 'like-new',
    estimatedValue: 350,
    location: 'Cairo',
    images: [
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600',
      'https://images.unsplash.com/photo-1546435770-a3e736b68c3e?w=600',
    ],
    tags: ['sony', 'headphones', 'noise-cancelling', 'wireless'],
    status: 'active',
    isFeatured: true,
    featuredUntil: '2024-04-20T00:00:00Z',
    viewCount: 234,
    savedCount: 18,
    createdAt: '2024-02-10T10:00:00Z',
    updatedAt: '2024-02-10T10:00:00Z',
    aiScore: 92,
    aiMatchReasons: ['Same category match', 'Similar value range', 'Same city'],
  },
  {
    id: 'prod-2',
    ownerId: 'user-1',
    title: 'iPad Pro 11" M2 (2022) 256GB',
    description: 'iPad Pro with Apple Pencil 2 included. Perfect condition, used at home for drawing and reading. No scratches on screen.',
    category: 'Electronics',
    subcategory: 'Tablets',
    condition: 'good',
    estimatedValue: 800,
    location: 'Cairo',
    images: [
      'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=600',
      'https://images.unsplash.com/photo-1587826080692-f439cd0b70da?w=600',
    ],
    tags: ['ipad', 'apple', 'tablet', 'pro'],
    status: 'pending',
    isFeatured: false,
    viewCount: 445,
    savedCount: 32,
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-03-01T10:00:00Z',
  },
  {
    id: 'prod-3',
    ownerId: 'user-2',
    title: 'Vintage Leather Jacket — Medium',
    description: 'Genuine leather, brown, medium size. Bought in Italy 3 years ago. Light wear, perfect for the season.',
    category: 'Fashion',
    subcategory: 'Outerwear',
    condition: 'good',
    estimatedValue: 220,
    location: 'Alexandria',
    images: [
      'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600',
    ],
    tags: ['leather', 'jacket', 'vintage', 'fashion'],
    status: 'active',
    isFeatured: false,
    viewCount: 156,
    savedCount: 24,
    createdAt: '2024-02-20T10:00:00Z',
    updatedAt: '2024-02-20T10:00:00Z',
    aiScore: 78,
    aiMatchReasons: ['Complementary category', 'Close value range'],
  },
  {
    id: 'prod-4',
    ownerId: 'user-3',
    title: 'Trek FX3 Disc Hybrid Bicycle',
    description: 'Excellent commuter bike. Full disc brakes, barely ridden. Comes with lock, lights, and bike bag.',
    category: 'Sports & Outdoors',
    subcategory: 'Cycling',
    condition: 'like-new',
    estimatedValue: 950,
    location: 'Giza',
    images: [
      'https://images.unsplash.com/photo-1532298229144-0ec0c57515c7?w=600',
    ],
    tags: ['bicycle', 'trek', 'commuter', 'cycling'],
    status: 'active',
    isFeatured: true,
    featuredUntil: '2024-04-15T00:00:00Z',
    viewCount: 389,
    savedCount: 41,
    createdAt: '2024-03-01T10:00:00Z',
    updatedAt: '2024-03-01T10:00:00Z',
  },
  {
    id: 'prod-5',
    ownerId: 'user-4',
    title: 'IKEA FRIHETEN Corner Sofa Bed',
    description: 'Beige corner sofa that converts to a bed. Great condition, no stains. Disassembly will be arranged.',
    category: 'Home & Garden',
    subcategory: 'Furniture',
    condition: 'good',
    estimatedValue: 600,
    location: 'Cairo',
    images: [
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600',
    ],
    tags: ['sofa', 'ikea', 'furniture', 'bed'],
    status: 'active',
    isFeatured: false,
    viewCount: 201,
    savedCount: 15,
    createdAt: '2024-02-05T10:00:00Z',
    updatedAt: '2024-02-05T10:00:00Z',
    aiScore: 65,
    aiMatchReasons: ['Different category, potential interest', 'Similar value'],
  },
  {
    id: 'prod-6',
    ownerId: 'user-4',
    title: 'Canon EOS R50 Mirrorless Camera',
    description: 'Perfect beginner camera. Only used for one photography workshop. Includes 18-45mm kit lens and two batteries.',
    category: 'Electronics',
    subcategory: 'Cameras',
    condition: 'like-new',
    estimatedValue: 750,
    location: 'Cairo',
    images: [
      'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=600',
    ],
    tags: ['canon', 'camera', 'mirrorless', 'photography'],
    status: 'active',
    isFeatured: true,
    featuredUntil: '2024-04-30T00:00:00Z',
    viewCount: 512,
    savedCount: 56,
    createdAt: '2024-01-20T10:00:00Z',
    updatedAt: '2024-01-20T10:00:00Z',
    aiScore: 88,
    aiMatchReasons: ['Same category', 'Very close value', 'Same city'],
  },
  {
    id: 'prod-7',
    ownerId: 'user-2',
    title: 'Dyson V11 Cordless Vacuum',
    description: 'Powerful cordless vacuum with all attachments. Works perfectly. Selling because I upgraded to a robot vacuum.',
    category: 'Home & Garden',
    subcategory: 'Appliances',
    condition: 'good',
    estimatedValue: 420,
    location: 'Alexandria',
    images: [
      'https://images.unsplash.com/photo-1558317374-067fb5f30001?w=600',
    ],
    tags: ['dyson', 'vacuum', 'cordless', 'cleaning'],
    status: 'active',
    isFeatured: false,
    viewCount: 178,
    savedCount: 12,
    createdAt: '2024-03-05T10:00:00Z',
    updatedAt: '2024-03-05T10:00:00Z',
  },
  {
    id: 'prod-8',
    ownerId: 'user-3',
    title: 'PlayStation 5 Digital Edition',
    description: 'PS5 Digital, no disc drive. In perfect working condition. Comes with 2 controllers and 4 games on PSN.',
    category: 'Electronics',
    subcategory: 'Gaming',
    condition: 'good',
    estimatedValue: 500,
    location: 'Giza',
    images: [
      'https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=600',
    ],
    tags: ['playstation', 'ps5', 'gaming', 'sony'],
    status: 'active',
    isFeatured: false,
    viewCount: 634,
    savedCount: 78,
    createdAt: '2024-02-28T10:00:00Z',
    updatedAt: '2024-02-28T10:00:00Z',
    aiScore: 85,
    aiMatchReasons: ['Electronics category match', 'Close value to your iPad'],
  },
]

// ── Swap Requests ─────────────────────────────────────────────

const mockTimeline = (events: Partial<SwapTimelineEvent>[]): SwapTimelineEvent[] =>
  events.map((e, i) => ({
    id: `evt-${i}`,
    swapId: '',
    event: e.event || '',
    description: e.description || '',
    actor: e.actor || 'system',
    actorId: e.actorId,
    createdAt: e.createdAt || new Date().toISOString(),
  }))

export const MOCK_SWAPS: SwapRequest[] = [
  {
    id: 'swap-1',
    requesterId: 'user-1',
    receiverId: 'user-4',
    offeredProductId: 'prod-1',
    requestedProductId: 'prod-6',
    status: 'approved',
    message: 'Hi Nour! I love your Canon R50. My Sony headphones are in perfect condition and similarly valued. Would you consider a swap?',
    adminNotes: 'Both products verified, values are comparable (350 EGP vs 750 EGP — user-1 offered to add coins to compensate). Approved.',
    adminReviewedBy: 'admin-1',
    adminReviewedAt: '2024-03-15T14:00:00Z',
    serviceFeeRequester: MOCK_SERVICE_FEE_EGP,
    serviceFeeReceiver: MOCK_SERVICE_FEE_EGP,
    requesterPaid: true,
    receiverPaid: false,
    exchangeMethod: 'meetup',
    meetupDetails: {
      city: 'Cairo',
      area: 'Maadi',
      meetingPoint: 'Cairo Festival City Mall — Main Entrance',
      date: '2024-03-25',
      time: '14:00',
      additionalNotes: 'I will be wearing a blue jacket',
    },
    requesterConfirmed: false,
    receiverConfirmed: false,
    createdAt: '2024-03-10T09:00:00Z',
    updatedAt: '2024-03-16T10:00:00Z',
    timeline: mockTimeline([
      { event: 'Swap Requested', description: 'Alex sent a swap request to Nour', actor: 'requester', actorId: 'user-1', createdAt: '2024-03-10T09:00:00Z' },
      { event: 'Interest Accepted', description: 'Nour accepted the swap interest', actor: 'receiver', actorId: 'user-4', createdAt: '2024-03-11T11:00:00Z' },
      { event: 'Discussion Started', description: 'Both parties entered the discussion panel', actor: 'system', createdAt: '2024-03-11T11:01:00Z' },
      { event: 'Sent to Admin Review', description: 'Swap submitted for admin approval', actor: 'system', createdAt: '2024-03-14T10:00:00Z' },
      { event: 'Admin Approved', description: 'Admin reviewed and approved the swap', actor: 'admin', actorId: 'admin-1', createdAt: '2024-03-15T14:00:00Z' },
      { event: 'Service Fee Paid', description: 'Alex paid the service fee (100 EGP)', actor: 'requester', actorId: 'user-1', createdAt: '2024-03-16T10:00:00Z' },
    ]),
  },
  {
    id: 'swap-2',
    requesterId: 'user-2',
    receiverId: 'user-1',
    offeredProductId: 'prod-3',
    requestedProductId: 'prod-1',
    status: 'in_discussion',
    message: 'Your headphones look amazing! I have a genuine leather jacket from Italy — would you swap?',
    serviceFeeRequester: MOCK_SERVICE_FEE_EGP,
    serviceFeeReceiver: MOCK_SERVICE_FEE_EGP,
    requesterPaid: false,
    receiverPaid: false,
    requesterConfirmed: false,
    receiverConfirmed: false,
    createdAt: '2024-03-18T10:00:00Z',
    updatedAt: '2024-03-19T12:00:00Z',
    timeline: mockTimeline([
      { event: 'Swap Requested', description: 'Sara sent a swap request to Alex', actor: 'requester', actorId: 'user-2', createdAt: '2024-03-18T10:00:00Z' },
      { event: 'Interest Accepted', description: 'Alex accepted the swap interest', actor: 'receiver', actorId: 'user-1', createdAt: '2024-03-19T12:00:00Z' },
      { event: 'Discussion Started', description: 'Both parties entered the discussion panel', actor: 'system', createdAt: '2024-03-19T12:01:00Z' },
    ]),
  },
  {
    id: 'swap-3',
    requesterId: 'user-3',
    receiverId: 'user-4',
    offeredProductId: 'prod-4',
    requestedProductId: 'prod-5',
    status: 'under_review',
    message: 'Your sofa bed looks great! I have a Trek bicycle in like-new condition. I think the values are comparable.',
    adminNotes: '',
    serviceFeeRequester: MOCK_SERVICE_FEE_EGP,
    serviceFeeReceiver: MOCK_SERVICE_FEE_EGP,
    requesterPaid: false,
    receiverPaid: false,
    requesterConfirmed: false,
    receiverConfirmed: false,
    createdAt: '2024-03-17T08:00:00Z',
    updatedAt: '2024-03-20T09:00:00Z',
    timeline: mockTimeline([
      { event: 'Swap Requested', description: 'Omar sent a swap request to Nour', actor: 'requester', actorId: 'user-3', createdAt: '2024-03-17T08:00:00Z' },
      { event: 'Interest Accepted', description: 'Nour accepted the swap interest', actor: 'receiver', actorId: 'user-4', createdAt: '2024-03-18T09:00:00Z' },
      { event: 'Discussion Started', description: 'Discussion phase began', actor: 'system', createdAt: '2024-03-18T09:01:00Z' },
      { event: 'Submitted for Review', description: 'Omar submitted swap for admin review', actor: 'system', createdAt: '2024-03-20T09:00:00Z' },
    ]),
  },
  {
    id: 'swap-4',
    requesterId: 'user-1',
    receiverId: 'user-3',
    offeredProductId: 'prod-2',
    requestedProductId: 'prod-8',
    status: 'completed',
    message: 'I would love to swap my iPad for your PS5. Both are great condition electronics!',
    adminNotes: 'Approved — values reasonably comparable.',
    adminReviewedBy: 'admin-1',
    adminReviewedAt: '2024-02-20T10:00:00Z',
    serviceFeeRequester: MOCK_SERVICE_FEE_EGP,
    serviceFeeReceiver: MOCK_SERVICE_FEE_EGP,
    requesterPaid: true,
    receiverPaid: true,
    exchangeMethod: 'meetup',
    meetupDetails: {
      city: 'Cairo',
      area: 'Mohandessin',
      meetingPoint: 'Arkan Plaza Mall',
      date: '2024-03-01',
      time: '12:00',
    },
    requesterConfirmed: true,
    receiverConfirmed: true,
    requesterRatingId: 'rating-1',
    receiverRatingId: 'rating-2',
    createdAt: '2024-02-10T10:00:00Z',
    updatedAt: '2024-03-02T16:00:00Z',
    timeline: mockTimeline([
      { event: 'Swap Requested', description: 'Alex requested swap with Omar', actor: 'requester', actorId: 'user-1', createdAt: '2024-02-10T10:00:00Z' },
      { event: 'Interest Accepted', description: 'Omar accepted', actor: 'receiver', actorId: 'user-3', createdAt: '2024-02-11T10:00:00Z' },
      { event: 'Admin Approved', description: 'Admin approved the swap', actor: 'admin', actorId: 'admin-1', createdAt: '2024-02-20T10:00:00Z' },
      { event: 'Service Fee Paid', description: 'Both users paid service fees', actor: 'system', createdAt: '2024-02-21T09:00:00Z' },
      { event: 'Meetup Arranged', description: 'Meetup set for Arkan Plaza Mall', actor: 'system', createdAt: '2024-02-22T10:00:00Z' },
      { event: 'Swap Completed', description: 'Both users confirmed completion', actor: 'system', createdAt: '2024-03-02T16:00:00Z' },
    ]),
  },
  {
    id: 'swap-5',
    requesterId: 'user-2',
    receiverId: 'user-3',
    offeredProductId: 'prod-7',
    requestedProductId: 'prod-4',
    status: 'pending',
    message: "Your bicycle is exactly what I need for commuting! I have a Dyson V11 vacuum — would you be interested?",
    serviceFeeRequester: MOCK_SERVICE_FEE_EGP,
    serviceFeeReceiver: MOCK_SERVICE_FEE_EGP,
    requesterPaid: false,
    receiverPaid: false,
    requesterConfirmed: false,
    receiverConfirmed: false,
    createdAt: '2024-03-20T14:00:00Z',
    updatedAt: '2024-03-20T14:00:00Z',
    timeline: mockTimeline([
      { event: 'Swap Requested', description: 'Sara sent a swap request to Omar', actor: 'requester', actorId: 'user-2', createdAt: '2024-03-20T14:00:00Z' },
    ]),
  },
]

// ── Messages ──────────────────────────────────────────────────

export const MOCK_MESSAGES: Message[] = [
  {
    id: 'msg-1',
    swapId: 'swap-1',
    senderId: 'user-1',
    type: 'text',
    content: 'Hi Nour! Just wanted to confirm — the headphones are in perfect condition, original box included. Let me know if you need more photos.',
    isAdminVisible: true,
    isReported: false,
    createdAt: '2024-03-11T11:30:00Z',
    readBy: ['user-1', 'user-4'],
  },
  {
    id: 'msg-2',
    swapId: 'swap-1',
    senderId: 'user-4',
    type: 'text',
    content: "Thanks Alex! The Canon is also perfect. I'll send more photos soon. The value difference — are you okay compensating with coins?",
    isAdminVisible: true,
    isReported: false,
    createdAt: '2024-03-11T12:00:00Z',
    readBy: ['user-1', 'user-4'],
  },
  {
    id: 'msg-3',
    swapId: 'swap-1',
    senderId: 'user-1',
    type: 'text',
    content: "Yes, I am happy to add 200 coins to compensate for the value difference. Does that work for you?",
    isAdminVisible: true,
    isReported: false,
    createdAt: '2024-03-12T09:00:00Z',
    readBy: ['user-1', 'user-4'],
  },
  {
    id: 'msg-4',
    swapId: 'swap-1',
    senderId: 'user-4',
    type: 'text',
    content: "That works perfectly! Let's proceed to admin review.",
    isAdminVisible: true,
    isReported: false,
    createdAt: '2024-03-12T10:00:00Z',
    readBy: ['user-1', 'user-4'],
  },
  {
    id: 'msg-5',
    swapId: 'swap-1',
    senderId: 'system',
    type: 'system',
    content: 'This swap has been approved by the admin. You can now proceed to the exchange step.',
    isAdminVisible: true,
    isReported: false,
    createdAt: '2024-03-15T14:01:00Z',
    readBy: ['user-1', 'user-4'],
  },
  // Swap 2 messages
  {
    id: 'msg-6',
    swapId: 'swap-2',
    senderId: 'user-2',
    type: 'text',
    content: 'Hi Alex! The jacket is genuine leather, bought in Milan. Barely worn. I think the trade is fair!',
    isAdminVisible: true,
    isReported: false,
    createdAt: '2024-03-19T12:30:00Z',
    readBy: ['user-2'],
  },
  {
    id: 'msg-7',
    swapId: 'swap-2',
    senderId: 'user-1',
    type: 'text',
    content: 'Sounds great Sara! Can you share more photos of the jacket? Especially the inside lining and any wear marks.',
    isAdminVisible: true,
    isReported: false,
    createdAt: '2024-03-19T13:00:00Z',
    readBy: ['user-1', 'user-2'],
  },
]

// ── Ratings ───────────────────────────────────────────────────

export const MOCK_RATINGS: Rating[] = [
  {
    id: 'rating-1',
    swapId: 'swap-4',
    raterId: 'user-1',
    ratedUserId: 'user-3',
    score: 4,
    comment: 'Omar was punctual and the PS5 was exactly as described. Great swap!',
    tags: ['punctual', 'item-as-described', 'friendly'],
    createdAt: '2024-03-02T17:00:00Z',
  },
  {
    id: 'rating-2',
    swapId: 'swap-4',
    raterId: 'user-3',
    ratedUserId: 'user-1',
    score: 5,
    comment: "Alex was amazing — super communicative, iPad was pristine. Highly recommend!",
    tags: ['communicative', 'item-as-described', 'trustworthy'],
    createdAt: '2024-03-02T17:30:00Z',
  },
]

// ── Transactions ──────────────────────────────────────────────

export const MOCK_TRANSACTIONS: Transaction[] = [
  {
    id: 'tx-1',
    userId: 'user-1',
    swapId: 'swap-1',
    type: 'service_fee',
    amount: MOCK_SERVICE_FEE_EGP,
    currency: 'EGP',
    status: 'completed',
    description: 'Service fee for swap #swap-1 (Sony headphones ↔ Canon R50)',
    paymentMethod: 'Visa *4242',
    referenceNumber: 'SS-2024-001',
    createdAt: '2024-03-16T10:00:00Z',
  },
  {
    id: 'tx-2',
    userId: 'user-1',
    swapId: 'swap-4',
    type: 'service_fee',
    amount: MOCK_SERVICE_FEE_EGP,
    currency: 'EGP',
    status: 'completed',
    description: 'Service fee for swap #swap-4 (iPad Pro ↔ PS5)',
    paymentMethod: 'Visa *4242',
    referenceNumber: 'SS-2024-002',
    createdAt: '2024-02-21T09:00:00Z',
  },
  {
    id: 'tx-3',
    userId: 'user-1',
    type: 'coin-purchase',
    amount: 9.99,
    currency: 'EGP',
    status: 'completed',
    description: 'Purchased 200 coins (Starter Pack)',
    paymentMethod: 'Visa *4242',
    referenceNumber: 'SS-COINS-001',
    createdAt: '2024-03-10T08:00:00Z',
  },
]

// ── Reports ───────────────────────────────────────────────────

export const MOCK_REPORTS: Report[] = [
  {
    id: 'rep-1',
    reporterId: 'user-4',
    targetType: 'user',
    targetId: 'user-5',
    reason: 'Attempted external contact',
    description: 'User Karim tried to share his WhatsApp number in the discussion to avoid the platform.',
    status: 'resolved',
    adminNotes: 'User suspended. This is a confirmed platform bypass attempt.',
    resolvedBy: 'admin-1',
    resolvedAt: '2024-03-01T12:00:00Z',
    createdAt: '2024-02-28T15:00:00Z',
  },
  {
    id: 'rep-2',
    reporterId: 'user-2',
    targetType: 'product',
    targetId: 'prod-4',
    reason: 'Inaccurate product description',
    description: 'The bicycle has visible rust on the frame that was not mentioned in the listing.',
    status: 'under_review',
    createdAt: '2024-03-19T14:00:00Z',
  },
]

// ── Disputes ──────────────────────────────────────────────────

export const MOCK_DISPUTES: Dispute[] = [
  {
    id: 'disp-1',
    swapId: 'swap-4',
    openedBy: 'user-1',
    reason: 'Item not as described',
    description: 'The PS5 controller was missing and not mentioned in the original listing.',
    status: 'resolved-mutual',
    adminNotes: 'Both parties agreed to a partial coin refund. Issue resolved.',
    resolvedBy: 'admin-1',
    resolvedAt: '2024-03-05T10:00:00Z',
    createdAt: '2024-03-03T09:00:00Z',
  },
]

// ── Suspicious Activity ───────────────────────────────────────

export const MOCK_SUSPICIOUS: SuspiciousActivity[] = [
  {
    id: 'sus-1',
    userId: 'user-5',
    type: 'Platform Bypass Attempt',
    description: 'User attempted to share external contact details (WhatsApp number) in swap discussion',
    severity: 'high',
    isReviewed: true,
    reviewedBy: 'admin-1',
    reviewedAt: '2024-03-01T12:00:00Z',
    createdAt: '2024-02-28T15:00:00Z',
  },
  {
    id: 'sus-2',
    userId: 'user-3',
    type: 'Unusual Listing Pattern',
    description: 'Multiple product listings created within 10 minutes with identical descriptions',
    severity: 'medium',
    isReviewed: false,
    createdAt: '2024-03-18T20:00:00Z',
  },
]

// ── Categories ────────────────────────────────────────────────

const MOCK_CATEGORY_COUNTS: Record<string, number> = {
  Electronics: 1240,
  Fashion: 890,
  'Home & Garden': 654,
  'Sports & Outdoors': 432,
  'Books & Media': 321,
  Vehicles: 112,
  'Kids & Baby': 287,
  'Art & Collectibles': 198,
}

export const MOCK_CATEGORIES: Category[] = PRODUCT_CATEGORIES.map(category => ({
  ...category,
  productCount: MOCK_CATEGORY_COUNTS[category.name] ?? 0,
}))

// ── Coin Packages ─────────────────────────────────────────────

export const COIN_PACKAGES: CoinPackage[] = [
  { id: 'pkg-1', name: 'Starter', coins: 100, price: 4.99, isPopular: false },
  { id: 'pkg-2', name: 'Plus', coins: 300, price: 12.99, isPopular: true, bonus: 30 },
  { id: 'pkg-3', name: 'Pro', coins: 700, price: 24.99, isPopular: false, bonus: 100 },
  { id: 'pkg-4', name: 'Elite', coins: 1500, price: 49.99, isPopular: false, bonus: 300 },
]

// ── AI Recommendations ────────────────────────────────────────

export const MOCK_RECOMMENDATIONS: AIRecommendation[] = [
  {
    id: 'rec-1',
    userId: 'user-1',
    productId: 'prod-6',
    matchScore: 92,
    reasons: [
      { type: 'category', label: 'Same electronics category', weight: 30 },
      { type: 'value', label: 'Similar estimated value', weight: 25 },
      { type: 'location', label: 'Both in Cairo', weight: 20 },
      { type: 'condition', label: 'Both listed as like-new', weight: 17 },
    ],
    createdAt: '2024-03-20T08:00:00Z',
  },
  {
    id: 'rec-2',
    userId: 'user-1',
    productId: 'prod-8',
    matchScore: 85,
    reasons: [
      { type: 'category', label: 'Electronics match', weight: 30 },
      { type: 'value', label: 'Close value to your iPad', weight: 28 },
      { type: 'interest', label: 'Similar to items you saved', weight: 27 },
    ],
    createdAt: '2024-03-20T08:00:00Z',
  },
  {
    id: 'rec-3',
    userId: 'user-1',
    productId: 'prod-4',
    matchScore: 71,
    reasons: [
      { type: 'location', label: 'Close to your location', weight: 35 },
      { type: 'value', label: 'Reasonable value match', weight: 36 },
    ],
    createdAt: '2024-03-20T08:00:00Z',
  },
]

// ── Utility helpers ───────────────────────────────────────────

export function getUserById(id: string): User | undefined {
  return MOCK_USERS.find(u => u.id === id)
}

export function getProductById(id: string): Product | undefined {
  return MOCK_PRODUCTS.find(p => p.id === id)
}

export function getSwapById(id: string): SwapRequest | undefined {
  return MOCK_SWAPS.find(s => s.id === id)
}

export function getProductsByUser(userId: string): Product[] {
  return MOCK_PRODUCTS.filter(p => p.ownerId === userId)
}

export function getSwapsByUser(userId: string): SwapRequest[] {
  return MOCK_SWAPS.filter(s => s.requesterId === userId || s.receiverId === userId)
}

export function getMessagesBySwap(swapId: string): Message[] {
  return MOCK_MESSAGES.filter(m => m.swapId === swapId)
}
